/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function my_init_function(): void;
export function __wbg_jscol_free(a: number): void;
export function jscol_new(a: number, b: number, c: number): number;
export function jscol_to_hex(a: number, b: number): void;
export function jscol_rfloat(a: number): number;
export function jscol_gfloat(a: number): number;
export function jscol_bfloat(a: number): number;
export function __wbg_colordot_free(a: number): void;
export function __wbg_get_colordot_color(a: number): number;
export function __wbg_set_colordot_color(a: number, b: number): void;
export function __wbg_get_colordot_posx(a: number): number;
export function __wbg_set_colordot_posx(a: number, b: number): void;
export function __wbg_get_colordot_posy(a: number): number;
export function __wbg_set_colordot_posy(a: number, b: number): void;
export function __wbg_get_colordot_posz(a: number): number;
export function __wbg_set_colordot_posz(a: number, b: number): void;
export function draw_triangle(a: number, b: number, c: number, d: number, e: number): void;
export function draw_meshed_triangle(a: number, b: number, c: number, d: number, e: number): void;
export function get_neutral(a: number): number;
export function color_to_dot(a: number): number;
export function temp_boost(a: number, b: number): number;
export function get_meshed_triangle(a: number, b: number, c: number, d: number, e: number): void;
export function get_gamut_cage(a: number, b: number, c: number, d: number): void;
export function __wbg_point2_free(a: number): void;
export function get_isotherm(a: number, b: number): void;
export function __wbg_set_point2_x(a: number, b: number): void;
export function __wbg_set_point2_y(a: number, b: number): void;
export function __wbg_get_point2_x(a: number): number;
export function __wbg_get_point2_y(a: number): number;
export function make_jscol(a: number, b: number, c: number): number;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_exn_store(a: number): void;
